name: Docker Publish

on:
  push:
    branches:
      - main # Assuming 'main' is the default branch, adjust if it's 'master'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/korjavin/dishduty/backend:latest
            ghcr.io/korjavin/dishduty/backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/korjavin/dishduty/frontend:latest
            ghcr.io/korjavin/dishduty/frontend:${{ github.sha }}